### ISSUE TITLE
Adding static 'option list' results in 'Uncaught ReferenceError: defineMessages is not defined'

### ISSUE THREAD

**Issue by mattvirlee** [collectionspace/cspace-ui.js#97]
Attempting to update the index.html file in `/usr/local/share/apache-tomcat-7.0.64/webapps/cspace#publicart`

Below the `plugins:` parameter, inserted the example list given at: https://github.com/collectionspace/cspace-ui.js/blob/master/docs/configuration/OptionListConfiguration.md
```
optionLists: {
    distanceUnits: {
      values: [
        'millimeters',
        'centimeters',
        'meters',
      ],
      messages: defineMessages({
        carats: {
          id: 'option.distanceUnits.millimeters',
          defaultMessage: 'mm',
        },
        centimeters: {
          id: 'option.distanceUnits.centimeters',
          defaultMessage: 'cm',
        },
        meters: {
          id: 'option.distanceUnits.meters',
          defaultMessage: 'm',
        },
      }),
    },
    },
```
**Note! the first item in the `defineMessages` list above is given as 'carats' - I assumed this was supposed to be millimeters and updated the list as such.**

This addition results in a white screen on the UI and an error in the console:
> Uncaught ReferenceError: defineMessages is not defined at login:40

Further attempted a custom list based on field in Public Art tenant 'acquisitionMethod' with the same result.

**Comment by mattvirlee** [comment]
Example of modified file:

[index.txt](https://github.com/collectionspace/cspace-ui.js/files/2133850/index.txt)

**Comment by ray-lee** [comment]
Yes, 'carats' should be 'millimeters'.

I assume your goal is to add new values to option lists. There should be more documentation around this. The `defineMessages` call is optional, and is typically only going to be used when you create a plugin, not when you do configuration in the html file.

In my experience the best practice is to make your option list values identical to the display labels. This makes it easier when you write reports; if you need to display the value of an option list in a report, you don't need to do any translation to get to the display label. If you do that, then you can omit the messages, because the value will be displayed in the UI if there is no corresponding message.

Here's what that would look like:

```
optionLists: {
    distanceUnits: {
      values: [
        'parsecs',
        'light years',
        'astronomical units',
      ],
      // No messages, so the values will be used for display
    },
},
```

If you do need a display label to be different than a value, and you're configuring the option list in the html file, you can omit the call to `defineMessages`, and just set messages to an object:

```
optionLists: {
    distanceUnits: {
      values: [
        'parsecs',
        'light years',
        'astronomical units',
      ],
      messages: {
        // The astronomical units value should be displayed differently
        'astronomical units': {
          id: 'option.distanceUnits.astronomical units',
          defaultMessage: 'AU',
        },
      },
    },
},
```

That's because `defineMessages` doesn't really do anything. It just returns the object that it receives as an argument. Its purpose is to serve as a marker for locating and processing message definitions when a plugin is compiled. When you do configuration in the html file, it doesn't go through that compile process, so there's no need for `defineMessages`.

**Comment by mattvirlee** [comment]
Thanks, that helps steer me in the right direction. My intention is to populate the list 'acquisitionMethod' in the Public Art tenant (acquisitions record type).

I've added the desired values to the index.html file, like so:
`optionLists: {
                                    aquisitionMethod: {
                                      values: [
                                      'developers',
                                      'direct purchase',
                                      'donations',
                                      'foundation grant',
                                      'grant',
                                      'in-kind',
                                      'municipal bonds',
                                      'percent for art',
                                      'private',
                                      'private and public',
                                      'public art ordinance',
                                      'state appropriations',
                                      'tax appropriation',
                                      'tax increment finance',
                                      'transportation enhancement program',
                                      ],
                                      // No messages, so the values will be used for display
                                    },
                                },`

I no longer get the error described in the original post, however when viewing an Acquisition record in the UI, the list is not populated. Is there an additional step that must be done?

**Comment by ray-lee** [comment]
The problem there is that the name of that option list is `acquisitionMethods` (s at the end). By convention, option list names are pluralized. I think there's a need for a way to discover the names of option lists associated with fields without looking at source. There are a bunch you can guess by knowing the field name and pluralizing it, but some you can't.

That field is defined here: https://github.com/collectionspace/cspace-ui.js/blob/master/src/plugins/recordTypes/acquisition/fields.js#L156

**Comment by ray-lee** [comment]
Oh, sorry. In the public art profile, the acquisitionMethod field is customized to be a dynamic term list (that's why it makes a request to populate the list). So you don't need to do any configuration to change the values. Go to the Administration/Term Lists screen in the UI, select Acquisition Methods, and add/remove/rename the terms there.

**Comment by ray-lee** [comment]
Ah, sorry again. The 404 means that the list hasn't been initialized, which should be happening on startup.

**Comment by remillet** [comment]
Matt, if you want to modify the default set of terms that appear automatically in each new instance of the Public Art profile you create, you can modify the acquisitionMethod terms in the App layer config:  see: https://github.com/collectionspace/application/blob/8d842e3f769cd4cda991bed1f28f9dc8bcf9d55c/tomcat-main/src/main/resources/tenants/publicart/domain-instance-vocabularies.xml#L81

Unless you want to make a request to change the Public Art profile, you can create your own fork or branch to track the term (and any other) changes you want to make.

**Comment by mattvirlee** [comment]
Thanks all - it looks like the 'AquisitionMethod' list has been included in the master branch of the application repo.

Am I correct in assuming that when I pull changes in and rebuild the application layer that it will have those changes? If so, you can feel free to close this issue as my question has been answered.
